# Generated by Django 3.1.7 on 2021-04-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
