# Generated by Django 3.1.7 on 2021-04-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_daftar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daftar',
        ),
    ]
