# Generated by Django 3.1.7 on 2021-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_auto_20210331_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumbotron',
            name='judul',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publised', 'Publised'), ('draft', 'Draft')], default='draft', max_length=9),
        ),
    ]
