# Generated by Django 3.1.7 on 2021-04-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_auto_20210404_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori2',
            field=models.CharField(choices=[('sastra', 'Sastra'), ('filsafat', 'Filsafat'), ('sejarah', 'Sejarah'), ('sosial-politik', 'Sosial-Politik')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.kelompok'),
        ),
    ]
