# Generated by Django 3.1.7 on 2021-04-04 15:50

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('my_blog', '0008_auto_20210404_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kategori2',
            field=models.CharField(choices=[('sejarah', 'Sejarah'), ('filsafat', 'Filsafat'), ('none', 'None'), ('sosial-politik', 'Sosial-Politik'), ('sastra', 'Sastra')], default='none', max_length=15),
        ),
    ]
