# Generated by Django 3.1.7 on 2021-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_auto_20210404_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori2',
            field=models.CharField(choices=[('opini', 'Opini'), ('sosial-politik', 'Sosial-Politik'), ('sastra', 'Sastra'), ('none', 'None'), ('sejarah', 'Sejarah'), ('filsafat', 'Filsafat')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publised', 'Publised')], default='draft', max_length=9),
        ),
    ]
