# Generated by Django 3.1.7 on 2021-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0010_auto_20210412_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori2',
            field=models.CharField(choices=[('sejarah', 'Sejarah'), ('sastra', 'Sastra'), ('filsafat', 'Filsafat'), ('sosial-politik', 'Sosial-Politik'), ('none', 'None'), ('opini', 'Opini')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publised', 'Publised'), ('draft', 'Draft')], default='draft', max_length=9),
        ),
    ]
