# Generated by Django 3.1.7 on 2021-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0023_auto_20210414_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publised', 'Publised'), ('draft', 'Draft')], default='draft', max_length=9),
        ),
    ]
