# Generated by Django 3.1.7 on 2021-04-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0024_auto_20210414_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jumbotron',
        ),
    ]
