# Generated by Django 3.1.7 on 2021-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0026_auto_20210419_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publised', 'Publised'), ('draft', 'Draft')], default='draft', max_length=9),
        ),
    ]
