# Generated by Django 3.1.7 on 2021-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0027_auto_20210419_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publised', 'Publised')], default='draft', max_length=9),
        ),
    ]
