# Generated by Django 3.1.7 on 2021-04-19 15:47

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(null=True, upload_to='cover/')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('publised', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publised', 'Publised')], default='draft', max_length=9)),
                ('Genre', models.CharField(blank=True, default='Buku', max_length=25)),
            ],
        ),
    ]
